/**
 * KMC Bus Tracker — Email Report Server (ESM version)
 * Run with: node server.js
 */

import 'dotenv/config';
import express    from 'express';
import cors       from 'cors';
import nodemailer from 'nodemailer';
import cron       from 'node-cron';

const app  = express();
const PORT = process.env.PORT || 3001;

// ── Middleware ────────────────────────────────────────────────
app.use(cors({ origin: '*' }));
app.use(express.json({ limit: '30mb' }));

// ── Nodemailer transporter ────────────────────────────────────
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

transporter.verify((err) => {
  if (err) {
    console.error('❌ Email transporter error:', err.message);
    console.error('   Check EMAIL_USER and EMAIL_PASS in your .env file');
  } else {
    console.log('✅ Email transporter ready');
  }
});

// ── In-memory schedule store ──────────────────────────────────
const activeSchedules = {};

// ── Build email HTML body ─────────────────────────────────────
function buildEmailBody(payload) {
  const now = new Date().toLocaleString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  return `
    <div style="font-family:Arial,sans-serif;background:#07090f;color:#e2e8f0;padding:32px;max-width:600px;margin:0 auto;border-radius:8px;">
      <div style="border-top:3px solid #dc2626;padding-top:20px;margin-bottom:24px;">
        <h1 style="color:#fff;font-size:20px;margin:0 0 4px;letter-spacing:.1em;text-transform:uppercase;">
          KMC Bus Production Tracker
        </h1>
        <p style="color:#475569;font-size:12px;margin:0;font-family:monospace;">Dashboard Report · ${now}</p>
      </div>
      <div style="background:rgba(13,21,38,.8);border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:20px;margin-bottom:20px;">
        <p style="color:#94a3b8;font-size:13px;margin:0 0 12px;">Please find attached the latest KMC Bus Production Dashboard report.</p>
        <p style="color:#64748b;font-size:12px;margin:0;font-family:monospace;">
          Buses on floor: <strong style="color:#f1f5f9;">${payload.busCount || '—'}</strong>
        </p>
        ${payload.schedule !== 'now' ? `
        <p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">
          Schedule: <strong style="color:#f1f5f9;">${
            payload.schedule === 'daily'
              ? `Daily at ${payload.scheduledTime}`
              : `Every ${payload.weekday} at ${payload.scheduledTime}`
          }</strong>
        </p>` : ''}
      </div>
      <div style="border-top:1px solid rgba(255,255,255,.06);padding-top:16px;font-size:10px;color:#1e2d40;font-family:monospace;letter-spacing:.06em;">
        KIIRA MOTORS CORPORATION — CONFIDENTIAL · Auto-generated by KMC Bus Tracker
      </div>
    </div>
  `;
}

// ── Build attachments from base64 data URLs ───────────────────
function buildAttachments(attachments = []) {
  return attachments
    .filter(a => a.dataUrl && a.filename)
    .map(a => {
      const [header, base64data] = a.dataUrl.split(',');
      const mimeType = header.match(/:(.*?);/)?.[1] || 'image/png';
      return { filename: a.filename, content: base64data, encoding: 'base64', contentType: mimeType };
    });
}

// ── Send email ────────────────────────────────────────────────
async function sendEmail(payload) {
  const to = payload.to.split(',').map(e => e.trim()).filter(Boolean).join(', ');
  const info = await transporter.sendMail({
    from:        process.env.EMAIL_FROM || process.env.EMAIL_USER,
    to,
    subject:     payload.subject || 'KMC Bus Production Dashboard Report',
    html:        buildEmailBody(payload),
    attachments: buildAttachments(payload.attachments),
  });
  console.log(`📧 Email sent → ${to} [${info.messageId}]`);
  return info;
}

// ── POST /api/send-report ─────────────────────────────────────
app.post('/api/send-report', async (req, res) => {
  const payload = req.body;
  if (!payload.to) return res.status(400).json({ error: 'Missing recipient (to)' });

  try {
    await sendEmail(payload);

    if (payload.schedule === 'daily' || payload.schedule === 'weekly') {
      const scheduleId = `${payload.to}_${payload.schedule}_${Date.now()}`;
      let cronExpr;

      if (payload.schedule === 'daily') {
        const [hour, minute] = (payload.scheduledTime || '08:00').split(':');
        cronExpr = `${parseInt(minute)} ${parseInt(hour)} * * *`;
      } else {
        const dayMap = { SUN:0, MON:1, TUE:2, WED:3, THU:4, FRI:5, SAT:6 };
        const day = dayMap[payload.weekday] ?? 1;
        const [hour, minute] = (payload.scheduledTime || '08:00').split(':');
        cronExpr = `${parseInt(minute)} ${parseInt(hour)} * * ${day}`;
      }

      // Cancel existing schedules for same recipient
      for (const [id, entry] of Object.entries(activeSchedules)) {
        if (entry.payload.to === payload.to) {
          entry.job.stop();
          delete activeSchedules[id];
          console.log(`🗑 Cancelled old schedule for ${payload.to}`);
        }
      }

      const job = cron.schedule(cronExpr, async () => {
        console.log(`⏰ Running scheduled send for ${payload.to}`);
        try { await sendEmail(payload); } catch (e) { console.error('Scheduled send error:', e.message); }
      }, { timezone: 'Africa/Kampala' });

      activeSchedules[scheduleId] = { job, payload };
      console.log(`📅 Scheduled [${payload.schedule}] "${cronExpr}" for ${payload.to}`);

      return res.json({ ok: true, sent: true, scheduled: true, scheduleId, cron: cronExpr });
    }

    res.json({ ok: true, sent: true, scheduled: false });
  } catch (err) {
    console.error('Send error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/schedules ────────────────────────────────────────
app.get('/api/schedules', (req, res) => {
  const list = Object.entries(activeSchedules).map(([id, e]) => ({
    id, to: e.payload.to, schedule: e.payload.schedule,
    scheduledTime: e.payload.scheduledTime, weekday: e.payload.weekday,
  }));
  res.json({ schedules: list });
});

// ── DELETE /api/schedules/:id ─────────────────────────────────
app.delete('/api/schedules/:id', (req, res) => {
  const { id } = req.params;
  if (activeSchedules[id]) {
    activeSchedules[id].job.stop();
    delete activeSchedules[id];
    res.json({ ok: true, cancelled: id });
  } else {
    res.status(404).json({ error: 'Schedule not found' });
  }
});

// ── Health check ──────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({ ok: true, schedules: Object.keys(activeSchedules).length, time: new Date().toISOString() });
});

// ── Start ─────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log('');
  console.log('🚌 KMC Email Server running');
  console.log(`   http://localhost:${PORT}`);
  console.log(`   POST /api/send-report`);
  console.log('');
});
