/**
 * POST /api/send-report — emails the dashboard report (PNG + PDFs built in the
 * browser) to the recipients typed in the Email Report dialog. Signed-in
 * tracker users only; sent through api/_lib/mailer.js.
 */
import { sendMail, MailError, escapeHtml } from './_lib/mailer.js';
import { requireSession } from './_lib/auth.js';

function buildEmailBody(payload, sender) {
  const now = new Date().toLocaleString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZone: 'Africa/Kampala',
  });
  return `
    <div style="font-family:Arial,sans-serif;background:#07090f;color:#e2e8f0;padding:32px;max-width:600px;margin:0 auto;border-radius:8px;">
      <div style="border-top:3px solid #dc2626;padding-top:20px;margin-bottom:24px;">
        <h1 style="color:#fff;font-size:20px;margin:0 0 4px;letter-spacing:.1em;text-transform:uppercase;">
          KMC Bus Production Tracker
        </h1>
        <p style="color:#475569;font-size:12px;margin:0;font-family:monospace;">Dashboard Report · ${escapeHtml(now)}</p>
      </div>
      <div style="background:rgba(13,21,38,.8);border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:20px;margin-bottom:20px;">
        <p style="color:#94a3b8;font-size:13px;margin:0 0 12px;">Please find attached the latest KMC Bus Production Dashboard report.</p>
        <p style="color:#64748b;font-size:12px;margin:0;font-family:monospace;">
          Buses on floor: <strong style="color:#f1f5f9;">${escapeHtml(payload.busCount ?? '—')}</strong>
        </p>
        ${payload.filterSummary ? `<p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">Filters: <strong style="color:#f1f5f9;">${escapeHtml(payload.filterSummary)}</strong></p>` : ''}
        ${payload.schedule && payload.schedule !== 'now' ? `<p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">Schedule: <strong style="color:#f1f5f9;">${
          escapeHtml(payload.schedule === 'daily' ? `Daily at ${payload.scheduledTime}` : `Every ${payload.weekday} at ${payload.scheduledTime}`)
        }</strong></p>` : ''}
        <p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">Sent by: <strong style="color:#f1f5f9;">${escapeHtml(sender)}</strong></p>
      </div>
      <div style="border-top:1px solid rgba(255,255,255,.06);padding-top:16px;font-size:10px;color:#1e2d40;font-family:monospace;letter-spacing:.06em;">
        KIIRA MOTORS CORPORATION — CONFIDENTIAL · Auto-generated by KMC Bus Tracker
      </div>
    </div>
  `;
}

const ALLOWED_TYPES = /^data:(application\/pdf|image\/png|image\/jpeg|application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet);base64,/;

function buildAttachments(attachments = []) {
  return attachments
    .filter(a => a && a.filename && ALLOWED_TYPES.test(String(a.dataUrl || '')))
    .slice(0, 6)
    .map(a => ({
      filename: String(a.filename).replace(/[\\/:*?"<>|\r\n]+/g, '_').slice(0, 120),
      content: String(a.dataUrl).split(',')[1],
      contentType: String(a.dataUrl).slice(5, String(a.dataUrl).indexOf(';')),
    }));
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin',  '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });

  const user = requireSession(req, res);
  if (!user) return;

  const payload = req.body || {};
  if (!payload.to) return res.status(400).json({ error: 'Enter at least one recipient.' });

  try {
    const r = await sendMail({
      to: payload.to,
      subject: String(payload.subject || 'KMC Bus Production Dashboard Report').slice(0, 200),
      html: buildEmailBody(payload, user.username),
      attachments: buildAttachments(payload.attachments),
    });
    return res.json({ ok: true, sent: true, scheduled: false, ...r });
  } catch (err) {
    const status = err instanceof MailError ? err.status : 500;
    console.error('send-report:', err.message);
    return res.status(status).json({ error: err.message });
  }
}
