import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

// ── In-memory schedule store (persists only within a single function instance) ─
// For persistent scheduling use Vercel Cron + a database or Vercel KV.
const activeSchedules = globalThis.__kmcSchedules ?? (globalThis.__kmcSchedules = {});

function buildEmailBody(payload) {
  const now = new Date().toLocaleString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  return `
    <div style="font-family:Arial,sans-serif;background:#07090f;color:#e2e8f0;padding:32px;max-width:600px;margin:0 auto;border-radius:8px;">
      <div style="border-top:3px solid #dc2626;padding-top:20px;margin-bottom:24px;">
        <h1 style="color:#fff;font-size:20px;margin:0 0 4px;letter-spacing:.1em;text-transform:uppercase;">
          KMC Bus Production Tracker
        </h1>
        <p style="color:#475569;font-size:12px;margin:0;font-family:monospace;">Dashboard Report · ${now}</p>
      </div>
      <div style="background:rgba(13,21,38,.8);border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:20px;margin-bottom:20px;">
        <p style="color:#94a3b8;font-size:13px;margin:0 0 12px;">Please find attached the latest KMC Bus Production Dashboard report.</p>
        <p style="color:#64748b;font-size:12px;margin:0;font-family:monospace;">
          Buses on floor: <strong style="color:#f1f5f9;">${payload.busCount || '—'}</strong>
        </p>
        ${payload.filterSummary ? `<p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">Filters: <strong style="color:#f1f5f9;">${payload.filterSummary}</strong></p>` : ''}
        ${payload.schedule !== 'now' ? `
        <p style="color:#64748b;font-size:12px;margin:8px 0 0;font-family:monospace;">
          Schedule: <strong style="color:#f1f5f9;">${
            payload.schedule === 'daily'
              ? `Daily at ${payload.scheduledTime}`
              : `Every ${payload.weekday} at ${payload.scheduledTime}`
          }</strong>
        </p>` : ''}
      </div>
      <div style="border-top:1px solid rgba(255,255,255,.06);padding-top:16px;font-size:10px;color:#1e2d40;font-family:monospace;letter-spacing:.06em;">
        KIIRA MOTORS CORPORATION — CONFIDENTIAL · Auto-generated by KMC Bus Tracker
      </div>
    </div>
  `;
}

function buildAttachments(attachments = []) {
  return attachments
    .filter(a => a.dataUrl && a.filename)
    .map(a => {
      const [, base64data] = a.dataUrl.split(',');
      return { filename: a.filename, content: base64data };
    });
}

async function sendEmail(payload) {
  const toList = payload.to.split(',').map(e => e.trim()).filter(Boolean);
  const from   = process.env.EMAIL_FROM || 'KMC Tracker <onboarding@resend.dev>';

  const result = await resend.emails.send({
    from,
    to:          toList,
    subject:     payload.subject || 'KMC Bus Production Dashboard Report',
    html:        buildEmailBody(payload),
    attachments: buildAttachments(payload.attachments),
  });
  return result;
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin',  '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });

  if (!process.env.RESEND_API_KEY) {
    return res.status(500).json({ error: 'RESEND_API_KEY not configured in Vercel environment variables.' });
  }

  const payload = req.body;
  if (!payload?.to) return res.status(400).json({ error: 'Missing recipient (to)' });

  try {
    const result = await sendEmail(payload);
    // The Resend SDK does NOT throw on API-level rejections (e.g. sandbox
    // mode restricting sends to unverified recipients) — it resolves with
    // { data: null, error: {...} } instead, so this must be checked explicitly
    // or a real failure gets reported back as a false success.
    if (result.error) {
      console.error('Resend rejected send-report:', result.error);
      return res.status(502).json({ error: result.error.message || 'Resend rejected the send.' });
    }
    res.json({ ok: true, sent: true, id: result.data?.id, scheduled: false });
  } catch (err) {
    console.error('Resend error:', err);
    res.status(500).json({ error: err.message });
  }
}
